### ISSUE TITLE
df_envimet.Geometry - DEM Matrix usability and issues

### ISSUE THREAD

**Issue by AntonelloDN** [AntonelloDN/df_envimet#2]
<p>Terrain does not work smoothly. It is necessary an improvement.</p>
<p>For detail see here:</p>
<a href="https://discourse.ladybug.tools/t/terrain-can-i-just-push-a-dem-matrix-into-the-inx/8014" >#terrain-can-i-just-push-a-dem-matrix-into-the-inx</a>

**Comment by idheitmann** [comment]
An example, with a closed mesh volume internalized.
[2020-02-17 Canyon df_envimet test.zip](https://github.com/AntonelloDN/df_envimet/files/4222262/2020-02-17.Canyon.df_envimet.test.zip)

**Comment by AntonelloDN** [comment]
@idheitmann,

I am at good point with a new method. It is also faster than previous one.
Here is a result:
DEM calculation time: 5354ms on my pc.
Grid size: 327; 324; 15
![image](https://user-images.githubusercontent.com/16763953/74885803-c08e0280-5376-11ea-91ce-6a3b01e2621f.png)
I need to test it to see if it is also good for simulation.

**Comment by idheitmann** [comment]
@AntonelloDN -- awesome, thank you! when can i get the new version? doesn't look like it's in the beta folder yet.

**Comment by AntonelloDN** [comment]
@idheitmann,
I have uploaded the new method. Envimet has fixed a bug about terrain in Envimet-core. Please, download envimet444 from ENVI_MET website and install it again.
